### ISSUE TITLE
Add a line wrap option

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Notes#160]

**Comment by trubitsyn** [comment]
Do you mean adding a "-" to a part of a string instead of letting the whole string go to the next line?

**Comment by tibbi** [comment]
no, what i probably mean is line wrap, not word wrap :p

**Comment by smichel17** [comment]
So, an option to disable line wrap (eg, for viewing code)?

**Comment by tibbi** [comment]
for viewing or comparing anything long, doesnt have to be code

**Comment by trubitsyn** [comment]
Would you accept a solution with a nested Fragment?

**Comment by tibbi** [comment]
what does that have to do with anything? O.o

**Comment by trubitsyn** [comment]
To disable wrapping MyEditText needs to be put inside a HorizontalScrollView. Since defining layout parameters at runtime would clutter the code a lot, we need to inflate a different view from XML somehow. Therefore, we either copy all the NoteFragment layout to a separate XML, or leave it and extract a changing part to another layout, that's where a nested fragment comes onto the stage.

**Comment by trubitsyn** [comment]
Two layouts are necessary since the scrolling behaviour is optional .

**Comment by tibbi** [comment]
I dont want to complicate it that much for sure, there has to be some flag we can use. I will see when I get there, not sure now.

**Comment by tibbi** [comment]
i dont know what's the cleanest solution, I dont mind wrapping the edittext in a horizontal scrollview

**Comment by tibbi** [comment]
not as clean solution as I wanted, but it seems to be working pretty often, so it's good enough
