### ISSUE TITLE
[feature request] automatic export of notes/persistent files

### ISSUE THREAD

**Issue by Wurzelmann** [SimpleMobileTools/Simple-Notes#364]
Right now, notes are not represented in the file system (at least not in the user space?) and it'd be very handy if every note were a file (txt or markdown for example) in order to be able to sync them across devices.

**Comment by HyknuF** [comment]
hi, is there something on the go with that? thanks a lot in advance

**Comment by GodlessGoat** [comment]
Currently it is possible to export a note to a txt-file and optionally synchronize the note with the file so that changes to the note are also applied to the file. However, if you want to do this for every note, you'll have to do it for each note individually, which becomes rather tedious.
I would really appreciate an option to automatically link each note with a txt-file.
