### ISSUE TITLE
Export and import all notes options

### ISSUE THREAD

**Issue by monblaz0** [SimpleMobileTools/Simple-Notes#422]
Hi,

having read issue #359 I wonder if you plan to get these options back in the app any time. Exporting and importing notes one by one is a tedious task, e.g. when changing phones or roms or making backups. By now I'm sticking to v.6.6.2 because of that.

What is more, it would be great if task notes were saved in a more human readable format, though I know changing a file format can be a pain.

Finally I have to say that the Pro versions of your apps are confusing me. I don't know what to expect about their availability on Fdroid. Could you clarify that issue please ? Thx

Good apps otherwise, thanx for your good work

**Comment by tibbi** [comment]
1. Exporting and Importing all notes has been removed due to Googles latest permissions policy changes, where apps like this wont be able to request the Storage permission anymore. So I cannot scan folders anymore, only individual files. 
2. I dont plan changing the way tasks are exported, they can be read just fine already, improving it isnt needed
3. F-droid contains only the Pro versions, the free ones arent available anymore.
Anyway, report 1 thing per issue in the future.

**Comment by monblaz0** [comment]
OK but everything that's on F-droid IS free so that doesn't make sense.
+ you never give a link to F-droid on your website. That's what really confused me.
