### ISSUE TITLE
add option to back up all notes at once. and import

### ISSUE THREAD

**Issue by h2dden** [SimpleMobileTools/Simple-Notes#484]
the current option: export a note as a text file is awsome as I can create txt files which then I can share via bluetooth and so on.
But if I have 10 note and would like to backup to move my notes to another device... 
please add an option to backup/export all notes and consequently to import all these into the app on another device

**Comment by tibbi** [comment]
it used to be there, but cannot be done anymore due to Googles latest permissions policy. Every file has to be allowed one by one, exporting multiple notes into 1 file isnt on the roadmap

**Comment by asl97** [comment]
Since this is the latest issue on the topic of export+import, I will comment here, mostly just to show that I am interested in this kind of feature.

Exporting and importing multiple notes into 1 file is basically the idea solution to my issue of moving to a new phone.

Basically a one time move, I personally don't really need syncing.

@tibbi I guess you seen `getExternalFilesDir()`?
Doesn't look that much more practical compare to something that can export all to one file and import it.

____
Guess I better get started manually exporting my 50+ notes one by one and maybe just do everything in acode afterwards.

CC: #422

**Comment by Aga-C** [comment]
@tibbi Would export everything to one file as a backup be prohibited by Google Play Store? I mean, that all notes could go to a single file, similarly as there is settings export in some apps (or all SMS export). In my opinion, there are two options:
- A single JSON file, that would serve purely as a backup - probably easiest to do, since using JSONs is simple.
- A single ZIP file, that would contain text files - that will also allow for easy import of multiple notes from other sources.

I think this feature would help a lot. Few days ago, I had to save all notes one by one to move them to a reinstalled app (and then import one by one). It would be a real time-saver if there could be a backup option.

**Comment by tibbi** [comment]
it could be done like that, its something I was thinking of too. I would do the JSON way, I dont like compressing stuff

**Comment by Aga-C** [comment]
@tibbi I'm working on it right now, but I have a dilemma - should I remove old export/import multiple notes functionality? From what I see, it's not available anymore on new Androids, but on old versions it's still possible to import the folder (without export multiple files).

**Comment by tibbi** [comment]
have 1 option for importing or exporting all only. If the old way is for Android 9-, have the new one on 10+
