### ISSUE TITLE
Add shortcuts for creating new note/checklist

### ISSUE THREAD

**Issue by tswistak** [SimpleMobileTools/Simple-Notes#495]
Hi,

I think it would be useful to have shortcuts for creating new note and new checklist, like it is in other note apps. I think that it would be best, if it could lead me directly to editing a new note, that already has prefilled some default title (like `untitled-[current-date]`). It would allow for quick taking of new notes (I can do an icon from a shortcut) instead of editing one particular note for which I have a widget or instead of having to do a lot of clicking to open an app and then create a new note.

For example, here's how it looks in OneNote (shortcuts translation: adding page (note), create todo checklist, insert photo, record sound):
![image](https://user-images.githubusercontent.com/9076255/150555436-48aa734b-2959-4ad6-a400-ccdd4e24a9e3.png)

and in built-in Notes app in OnePlus (shortcut translation: new note):
![image](https://user-images.githubusercontent.com/9076255/150555483-06f50809-b023-4a4d-8625-2fdddbc505eb.png)

In both apps, when I click a shortcut it leads me directly to a new note and I can start editing them right away.

**Comment by bigConifer** [comment]
Yeah, +1 for adding shortcuts.

However, please do not set default titles without confirmation. It are much more steps changing the title afterwards (which most users will do to keep track of their notes) instead of having as user to quickly go through the "new note" dialog after clicking on a shortcut in the same way as for the "new note" options inside the app.

In general it would be a great improvement of the "new note" dialog if the note title would be prefilled with a default (timestamp) and preselected at the same time. The keyboard should be still open. 
Thereby the users can decide whether they simply click OK to confirm the default title or if they want to overwrite it with a custom one by starting to type.

I think this would be the best compromise as it improves the workflow without significant degradations.

**Comment by tswistak** [comment]
>However, please do not set default titles without confirmation. It are much more steps changing the title afterwards (which most users will do to keep track of their notes) instead of having as user to quickly go through the "new note" dialog after clicking on a shortcut in the same way as for the "new note" options inside the app.

I don't agree. I'm using it in other apps to quickly write a note, I wouldn't like to be asked for the title. For example, in OneNote it looks like this:

https://user-images.githubusercontent.com/9076255/150669555-b2d31d8f-9390-4128-8edd-56463b3302a7.mp4

When it works this way, I can go straight-away to editing the note and if needed, I can always change the title. Moreover, date as a title is good, since even now, I don't always write a title, just rely on a date.
