### ISSUE TITLE
Request: Simple Dictionary and Simple Thesaurus 

### ISSUE THREAD

**Issue by Rbagman** [SimpleMobileTools/Simple-Notes#5]
I haven't found a decent/working FOSS dictionary or thesaurus since I bought my Android device. 

Aard installs but no dictionary and I can't seem to download Aard 2 from its site; DictionaryforMids is baaad --- does not make suggestions as you type does not spell/suggest.

**Comment by kTyn9A9Kw3** [comment]
For Aard 2 you should download apk files here because it's not available on F-Droid yet: http://github.com/itkach/aard2-android (aardict.org)

You may also want to take a look at: 
https://f-droid.org/app/org.kiwix.kiwixmobile
https://f-droid.org/app/org.wiktionary
https://f-droid.org/app/com.mitzuli
https://f-droid.org/app/de.reimardoeffinger.quickdic

**Comment by smichel17** [comment]
I believe this issue can now be closed, as I've re-created this in the general discussion repo. See ^ that link.
