### ISSUE TITLE
export / import notes not working

### ISSUE THREAD

**Issue by nopeppermint** [SimpleMobileTools/Simple-Notes#539]
I am using the latest version of simple notes pro v6.12.2 on an Android 8 based Smartphone.
From there I would like to export all my notes to another Smartphone with lineage os 18.1 (android 11).

I am able to export the note (see attached note)
[Test.tesr260622.txt](https://github.com/SimpleMobileTools/Simple-Notes/files/8986809/Test.tesr260622.txt)

But once I try to import them on the new phone, I get the following error:

```
Error:
com.google.gson.JsonSyntaxException:
java.lang.IllegalStateException: Expected
BEGIN_ARRAY but was STRING at line 1
column 1 path $
```

Can you please fix this?

It might be related to your latest export changes https://github.com/SimpleMobileTools/Simple-Notes/commit/15763d8c1a8a33f0cc85ff49bf39b8be937a498e

Did you forget to add that in the import?

Did you test the app before releasing it?

**Comment by tibbi** [comment]
that commit is unrelated. The "Import notes" feature expects multiple notes in a file, will make it more flexible soon.

**Comment by nopeppermint** [comment]
Hi Tibbi

As you closed the issue, I assumed it's working now.

But it still doesn't work, I updated to 6.12.3 on both device and reexported my notes.
But now the error message is different:

```
Error:
android.database.sqlite.SQLiteConstraintException: NOT NULL
constraint failed: notes.value (code 1299 SQLITE_CONSTRAINT_NOTNULL)
```

**Comment by nopeppermint** [comment]
but open file works, indeed

**Comment by jeyca** [comment]
I get the same sqlite error, but because @tibbi stated:

> The "Import notes" feature expects multiple notes in a file

what kind of file it expects? Can I somehow export all my notes to a single file? Because I have around 50 notes, and reading the other issues it looked to me like there is no such option. So I took the notes.db (with root access) and wrote a little script to create note files:

```
db = sqlite3.connect('databases/notes.db')
cursor = db.cursor()

cursor.execute('SELECT * FROM notes')
notes = cursor.fetchall()

for note in notes:
    filename = note[1].replace('/', '_')
    with open(f'notefiles/{filename}.txt', 'w') as f:
        f.write(note[2])
```

however, the "export" worked this way, but still I need to import each notefile one by one (no root access on new phone)

Open as file works, yes, but if there _is_ a way to import all notes together, I really would like to know.
