### ISSUE TITLE
Arrow back button

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Notes#58]
Hi! Please, add an Arrow back, to cancel words written / deleted

Or, alternatively, add the ability to save the new words manually, without autosave

**Comment by smichel17** [comment]
Could you elaborate on why you want this feature? 

My guess is that you want to be able to roll back changes if you accidentally deleted/modified something. If that's true, I think a 'history' feature, where you can browse prior autosaves and return to one of your choice, might work better for that purpose.

**Comment by AlfaOmega33** [comment]
True, is exactly what the reason, since I happened several times to lose notes in this way. For editing I believe that the historic will be fine for resolve the problem. 

- sorry for my bad english, I use Google Translate

**Comment by knezi** [comment]
So do you think a button that would display a list of past versions (of course with some preview) would be enough? Should be the history persistent throughout executions of the app? How many versions (and when do you make new version) should be kept?

Maybe just arrow back that would erase/insert one character at a time plus when held one word at a time would be enough. What do you think?

I can try to implement it, let's just discuss the exact form.

**Comment by smichel17** [comment]
The way I would do it is:

- `History` option in the overflow (three dot) menu changes to history view
- History view is like the normal view, except:
  - Title is "History", not "Notes"
  - To the left of the title, there is an X, to return to normal view
  - Instead of the title of a note, the scroll bar shows the date/time of the version
  - In the top bar, there are only three options:
    - A check mark, to restore the note currently scrolled to
    - An option to share that version of the history to another app
    - An option to save that version to a file

**Comment by tibbi** [comment]
I dont really feel that we need a history function for the past versions. Saving to / loading from files has been added recently, which can easily be used for saving a note in a synchronized folder of Dropbox or other cloud, that will automatically create backup and synchronize the notes across all devices.

Storing previous versions of notes could be a mess, what we could maybe add is an Undo button that will undo the actions only from the current session, something like at Draw.

**Comment by knezi** [comment]
@tibbi I agree, we don't need a history function. Undo button would do it, but it's right I really miss it.

As for backups, one has to save every file manually every time, so it's a bit hassle. It would be nice to be able to save all files at once.

**Comment by tibbi** [comment]
there is quite often an autosave triggered, on every pause or dialog open. If its not working properly in some cases, try reporting in which ones.

**Comment by knezi** [comment]
I haven't noticed any problem. It's just that I miss the back button.

**Comment by tibbi** [comment]
ye that could be added maybe as an actionmenu item. But only for the current session, dont overcomplicate it.

**Comment by knezi** [comment]
Yes, that's exactly what I meant. The use case:
I edit the note and incidentally erase or replace some text and I want to get it back just while editing.

**Comment by tibbi** [comment]
yes like that

**Comment by smichel17** [comment]
I think that would also be good enough. I'd keep the recent history around for as long as possible, though (eg, until `onDelete`, not `onPause` or `onStop`).

**Comment by tibbi** [comment]
yes it will be clear in onDestroy, which triggers if you quit the app by Back button, not if you go Home  or in Notes settings

**Comment by MahzunGozler** [comment]
Hi ! I was seeking for the same thing. Reading the conversion lets me think that  "arrow back that would erase/insert one character at a time plus when held one word at a time" and an history function are really 2 different things. 
I think the first one, arrow back, is really needed because it's really easyc when you try to erase few words to erase some word you don't want to and because of the autosave function,k it's impossible to cancel.
The 2nd one, history, is an interesting feature, but to my mind, it's really a bonus compare to the first. 
In fact, I really came here to create a feature resquest for the arrow back :)

**Comment by ilf** [comment]
I would also love an undo option. One step is enough. But I frequently select text and then accidentaly press a button on the keyboard, deleting my selection.

**Comment by GuitarBilly** [comment]
i also would request this option to undo an edit action in the current session.

I have most commonly mistakes with text selection as already mentionened and backspace deletions, e.g. if the cursor is not where you think it is,

**Comment by tibbi** [comment]
undo/redo for the current session will be added in version 4.1.0. I have to think of some UI change as it can be confusing now, lets see if it works at all first :p
