### ISSUE TITLE
You should be able to export/import all your notes into txt files

### ISSUE THREAD

**Issue by samontab** [SimpleMobileTools/Simple-Notes#592]
The simplest open standard for notes is a txt file.

You should be able to import and export all your notes from this format.

I see that you can import and export each one individually, but if you have more than a few then it gets complicated.

Since there's already the code needed to do a single import/export, it should be straight forward to do the same for all the notes.

Some typical use cases would be: bring your notes from another system, back up your own notes, or go to another system.

**Comment by tibbi** [comment]
you mean like Import folder?

**Comment by samontab** [comment]
Yes, an import folder where each note is stored as a txt file with the name of the file as the title of the note.

That's how other apps like [Notepad](https://github.com/farmerbb/Notepad) work.

**Comment by MaxsimLionel** [comment]
I second this. It makes it really easy to then take your "Notes" or "Documents" folder and drop it on your desktop and edit from there. I think the implementation of this would be best if the note taker app manages and reads/writes to files present in the filesystem, rather than creating it's own hidden database.
Like "Markor" on F-Droid does it. I really like that you make all your apps with the same design guidelines and simple settings.

**Comment by tibbi** [comment]
exporting is already possible
