### ISSUE TITLE
Note change does not trigger update of the associated file

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Notes#87]
It would be useful if someone preferred to save his notes in a particular folder on SD card.

**Comment by tibbi** [comment]
you can use the "Export as file" feature, there you can select a save folder. The file will be automatically updated on save.

**Comment by trubitsyn** [comment]
Exported as file, but the file does not get updated automatically after a note change. Am I doing sonething wrong?

**Comment by tibbi** [comment]
I see, guess it broke. It should be working like that.

**Comment by tibbi** [comment]
seems like not a bug, it wasnt planed to work like that so might need some more work.

**Comment by trubitsyn** [comment]
Imagine the following case:
- Import note from file A with auto-update
- Export note A to file B (**with auto-update after this patch**)
- Import note from file B (with auto-update)

Update A -> B updates -> Duplicate notes

So I think importing already exported note or exporting already imported note should be prohibited, because it can lead to confusion and unintended side effects.

**Comment by tibbi** [comment]
ye Id like to think it through to avoid some confusion. It can already be confusing in some cases.

**Comment by smichel17** [comment]
How important is the ability to use notes in different directories? What about different name/filename?

What if you just picked a single folder as your "notes folder", and then every note were stored (with auto-update) in that folder, and the file names would be `${note name}.txt`?

Then you don't have to worry about all the complexity that comes along with import/export. You do lose some functionality, but if that's not necessary functionality, maybe the trade-off is okay here.

**Comment by trubitsyn** [comment]
I agree that having a single "Notes" folder where one can drop his notes, edit and delete them is better. Moreover, that's *simpler*.

**Comment by tibbi** [comment]
It is important to have notes in different folders. The note can be relevant to the given folder, or some cloud syncing is in place, when you just pick a folder and everything in it will be synced with some cloud.

**Comment by smichel17** [comment]
I've never wanted to run multiple sync programs at once. So, in my use case I would make my "notes folder" one that is synced to nextcloud, and that would be fine.

I do agree, sometimes I would not like all my notes to be synced. But maybe the better solution is to allow app-only notes that are not written to the folder.

**Comment by smichel17** [comment]
Adding on, it would not be hard to allow adding multiple folders, which you could switch between using a navigation drawer in the app, or something. @tibbi I know you've historically been opposed to a drawer, because then the app is getting more complicated, but the menu is getting quite large already. I think you need to commit to either keeping the app simple, cutting down on features and options and accepting that some things simply won't be possible, or opening up the design space a little so the overflow menu is not the only place to put options and actions.

**Comment by tibbi** [comment]
I dont want to limit saving notes in 1 folder, that would make the app useles for a lot of people.
Im not going to add a navigation drawer anytime soon either, as its terrible user experience and its designed for switching between screens anyway, not for actions.

**Comment by user6529576559** [comment]
Something should be done about this because currently the only way I can keep my notes secure is to manually export all one-by-one and then encrypt them with other app and then upload it with an another app.

It would be nice to have an "Export all" option which would export every note into a separate .txt file, then they would be zipped into a zip file. Then this zip file could be saved onto disk or shared with an encryption app (gpg or whatever). Then it would be possible to upload the gpg file to somewhere. Of course the user could skip the encrypting step and share it with a syncing app in the first place.

I'm thinking about how to do this automatically but still keep the app simple. I think the app should not do encryption or syncing, these should be responsibilities of other apps. This would also make simple notes flexible, because any encryption and syncing method could be used.

Maybe a new app, "Simple Encryptor" should be created because it could be used for other apps (Simple Camera, Simple Draw, Simple Calendar, Simple Sound Recorder, etc.). The purpose of Simple Encryptor would be to encrypt stuff of course but with minimal permissions (no internet permission). In Simple Encryptor it would be possible to set the encryption method (public key and/or password, destination, etc.). But that is a different story.

**Comment by tibbi** [comment]
Ill take a look at it in the future when Ill be working on the Simple Notes. I dont want to spam every app with encryption related things for sure, people should just password protect their device and thats it.

**Comment by user6529576559** [comment]
Not that it annoys me, but the File Manager already has encryption (password protected hidden folders).

**Comment by tibbi** [comment]
thats a different thing. It just adds password protection to showing hidden files with the File Manager, you can still see them with other apps.

**Comment by user6529576559** [comment]
Then what is it good for then? What is the use case?

BTW in my previous larger comment, I was talking about encryption which takes place before uploading anything to the cloud. It is not for encrypting stuff to be encrypted on the phone, but to be uploaded to somewhere later. Nobody wants to upload plain text to any cloud provider, right?

**Comment by tibbi** [comment]
The vast majority of people have no problem using plain text anywhere, so encrypting everything isnt a priority now.
That hidden folder password protection is just a protection against children, or other third party (not device owner) gallery users from seeing hidden items. It was requested by quite many people, so its good enough for their use case.

**Comment by user6529576559** [comment]
> The vast majority of people have no problem using plain text anywhere
While this is a very sad thing, it is still true unfortunately.

Anyways, the encryption before uploading to the cloud provider should be done by a separate app.
So from the Notes app perspective the only thing what should be done is to make it easier to export all the notes at once, and do it automatically preferably.
After that, the user can do anything with other apps, upload from the export folder to cloud, or encrypt the files and then sync with the cloud, etc.
